version: "3.9"
services:
  postgres:
    image: postgres:14.3-alpine
    container_name: kotlin_practise
    ports:
      - "5440:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Password"
      PG_DATA: ./snap/postgres/data/pgdata